In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import statistics

In [4]:
sous_nutrition = pd.read_csv("C:/Livrables/DAN-P4-FAO/sous_nutrition.csv")
dispo_alimentaire = pd.read_csv("C:/Livrables/DAN-P4-FAO/dispo_alimentaire.csv")
aide_alimentaire = pd.read_csv("C:/Livrables/DAN-P4-FAO/aide_alimentaire.csv")
population = pd.read_csv("C:/Livrables/DAN-P4-FAO/population.csv")

In [5]:
dispo_alimentaire.fillna(0, inplace=True)

In [6]:
colonnes_en_kg = ['Aliments pour animaux', 'Disponibilité intérieure', 'Exportations - Quantité', 'Importations - Quantité', 'Nourriture', 'Pertes', 'Production', 'Semences', 'Traitement', 'Variation de stock', 'Autres Utilisations']
for i in colonnes_en_kg:
    dispo_alimentaire[i] *= 1000000

In [7]:
dispo_alimentaire.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000000.0,0.0,0.0,53000000.0,0.0,53000000.0,0.0,0.0,0.0
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0

In [8]:
population["Valeur"] *= 1000

In [9]:
aide_alimentaire.rename(columns={"Pays bénéficiaire": "Zone", "Valeur":"Aide_kg"}, inplace=True)
aide_alimentaire['Aide_kg'] *= 1000

In [10]:
sous_nutrition['Valeur'] = pd.to_numeric(sous_nutrition['Valeur'], errors='coerce')

In [11]:
sous_nutrition.fillna(0, inplace=True)

In [12]:
sous_nutrition.rename(columns={"Valeur": "sous_nutrition"}, inplace=True)

In [13]:
sous_nutrition['sous_nutrition'] *= 1000000

In [14]:
# Proportion de personnes en état de sous-nutrition

In [15]:
prop_sous_nutrition = pd.merge(population.loc[population['Année'] == 2017,["Zone", "Valeur"]],
                               sous_nutrition.loc[sous_nutrition['Année'] == '2016-2018',["Zone", "sous_nutrition"]],
                               on='Zone')

In [16]:
prop_sous_nutrition

                                       Zone      Valeur  sous_nutrition
0                               Afghanistan  36296113.0      10500000.0
1                            Afrique du Sud  57009756.0       3100000.0
2                                   Albanie   2884169.0        100000.0
3                                   Algérie  41389189.0       1300000.0
4                                 Allemagne  82658409.0             0.0
..                                      ...         ...             ...
198  Venezuela (République bolivarienne du)  29402484.0       8000000.0
199                                Viet Nam  94600648.0       6500000.0
200                                   Yémen  27834819.0             0.0
201                                  Zambie  16853599.0             0.0
202                                Zimbabwe  14236595.0             0.0

[203 rows x 3 columns]

In [17]:
Réponse1 = sum(prop_sous_nutrition['sous_nutrition']/sum(prop_sous_nutrition['Valeur'])*100)

In [18]:
print("la proportion de personnes en état de sous-nutrition est de :", round(Réponse1,2), "%")

la proportion de personnes en état de sous-nutrition est de : 7.13 %

In [19]:
# Dispo Alimentaire

In [20]:
dispo_alimentaire

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000000.0,0.0,0.0,53000000.0,0.0,53000000.0,0.0,0.0,0.0
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15600,Îles Salomon,Viande de Suides,animale,0.0,0.0,45.0,4.70,4.28,1.41,3000000.0,0.0,0.0,3000000.0,0.0,2000000.0,0.0,0.0,0.0
15601,Îles Salomon,Viande de Volailles,animale,0.0,0.0,11.0,3.34,0.69,1.14,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0
15602,Îles Salomon,"Viande, Autre",animale,0.0,0.0,0.0,0.06,0.00,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15603,Îles Salomon,Vin,vegetale,0.0,0.0,0.0,0.07,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15604,Îles Salomon,"Épices, Autres",vegetale,0.0,0.0,4.0,0.48,0.21,0.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
dispo_alimentaire = dispo_alimentaire.merge(population.loc[population['Année'] == 2017, ["Zone", "Valeur"]], on='Zone')

In [22]:
dispo_alimentaire['dispo_kcal'] = dispo_alimentaire['Disponibilité alimentaire (Kcal/personne/jour)'] * dispo_alimentaire ['Valeur'] * 365

In [23]:
dispo_alimentaire_totale_en_kcal = dispo_alimentaire['dispo_kcal'].sum()

In [24]:
dispo_alimentaire_totale_en_kcal

7635429388975815.0

In [25]:
potentiel_dhumains_nourrissables = round(dispo_alimentaire_totale_en_kcal/(2500*365))

In [26]:
potentiel_dhumains_nourrissables

8367593851

In [27]:
# Dispo alimentaire végétale

In [28]:
vegetal = dispo_alimentaire[dispo_alimentaire["Origine"].isin(['vegetale'])]

In [29]:
Réponse2 = vegetal['dispo_kcal'].sum()

In [30]:
print("la disponibilité intérieure végétale est de :", round(Réponse2))

la disponibilité intérieure végétale est de : 6300178937197865

In [31]:
# Part des animaux, des pertes et de nourriture dans la disponibilité intérieure

In [32]:
dispo_alimentaire

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Valeur,dispo_kcal
0,Afghanistan,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000000.0,0.0,0.0,53000000.0,0.0,53000000.0,0.0,0.0,0.0,36296113.0,6.624041e+10
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0,36296113.0,1.324808e+10
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0,36296113.0,1.324808e+10
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36296113.0,0.000000e+00
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0,36296113.0,5.299232e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15411,Îles Salomon,Viande de Suides,animale,0.0,0.0,45.0,4.70,4.28,1.41,3000000.0,0.0,0.0,3000000.0,0.0,2000000.0,0.0,0.0,0.0,636039.0,1.044694e+10
15412,Îles Salomon,Viande de Volailles,animale,0.0,0.0,11.0,3.34,0.69,1.14,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0,636039.0,2.553697e+09
15413,Îles Salomon,"Viande, Autre",animale,0.0,0.0,0.0,0.06,0.00,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,636039.0,0.000000e+00
15414,Îles Salomon,Vin,vegetale,0.0,0.0,0.0,0.07,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,636039.0,0.000000e+00
15415,Îles Salomon,"Épices, Autres",vegetale,0.0,0.0,4.0,0.48,0.21,0.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,636039.0,9.286169e+08

In [33]:
dispo_alim_animaux = dispo_alimentaire["Aliments pour animaux"].sum()
print("La disponibilité intérieure pour les animaux est de :", round(dispo_alim_animaux), "")

La disponibilité intérieure pour les animaux est de : 1288002000000

In [34]:
dispo_alim_nourriture = dispo_alimentaire["Nourriture"].sum()
print("La disponibilité intérieure pour la nourriture est de :", round(dispo_alim_nourriture))

La disponibilité intérieure pour la nourriture est de : 4805525000000

In [35]:
dispo_alim_pertes = dispo_alimentaire["Pertes"].sum()
print("La disponibilité intérieure perdue est de :", round(dispo_alim_pertes))

La disponibilité intérieure perdue est de : 452283000000

In [36]:
dispo_alim_autres = dispo_alimentaire["Autres Utilisations"].sum()
print("La disponibilité intérieure autre est de :", round(dispo_alim_autres))

La disponibilité intérieure autre est de : 858771000000

In [37]:
dispo_alim_semences = dispo_alimentaire["Semences"].sum()
print("La disponibilité intérieure pour les semences est de :", round(dispo_alim_semences))

La disponibilité intérieure pour les semences est de : 153317000000

In [38]:
dispo_interieure = dispo_alimentaire["Disponibilité intérieure"].sum()
print("La disponibilité intérieure totale est de :", round(dispo_interieure))

La disponibilité intérieure totale est de : 9733927000000

In [39]:
part_animaux = (dispo_alim_animaux/dispo_interieure)*100
print("La part pour les animaux est de :", round(part_animaux, 2), "%")

La part pour les animaux est de : 13.23 %

In [40]:
part_nourriture = (dispo_alim_nourriture/dispo_interieure)*100
print("La part pour la nourriture des humains est de :", round(part_nourriture, 2), "%")

La part pour la nourriture des humains est de : 49.37 %

In [41]:
part_pertes = (dispo_alim_pertes/dispo_interieure)*100
print("La part de perdue est de :", round(part_pertes, 2), "%")

La part de perdue est de : 4.65 %

In [42]:
# Utilisation des cérérales

In [43]:
diff_cereales = ["Blé et produits", "Riz et produits", "Orge et produits", "Maïs et produits", "Seigle et produits",
                  "Avoine", "Millet et produits", "Sorgho et produits", "Céréales, Autres"]

In [44]:
cereales = dispo_alimentaire.loc[dispo_alimentaire['Produit'].isin(diff_cereales),:]

In [45]:
print("% d'alimentation animale :", "{:.2f}".format(cereales['Aliments pour animaux'].sum()*100/cereales['Disponibilité intérieure'].sum()),"%")

% d'alimentation animale : 69.67 %

In [46]:
print("% d'alimentation humaine :", "{:.2f}".format(cereales['Nourriture'].sum()*100/cereales['Disponibilité intérieure'].sum()),"%")

% d'alimentation humaine : 17.63 %

In [47]:
# Manioc

In [48]:
sous_nutrition_thailande = prop_sous_nutrition.loc[prop_sous_nutrition['Zone'] == 'Thaïlande',:]
print('% de sous nutrition en Thaïlande :', "{:.2f}".format(sous_nutrition_thailande['sous_nutrition'].iloc[0]*100/sous_nutrition_thailande['Valeur'].iloc[0]), "%")

% de sous nutrition en Thaïlande : 8.96 %

In [49]:
# Manioc exporté

In [50]:
export_manioc = dispo_alimentaire.loc[(dispo_alimentaire['Produit'] == "Manioc") & (dispo_alimentaire['Zone'] == "Thaïlande"), :]

In [51]:
export_manioc

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Valeur,dispo_kcal
13620,Thaïlande,Manioc,vegetale,1.800000e+09,2.081000e+09,40.0,13.0,0.05,0.14,6.264000e+09,2.521400e+10,1.250000e+09,871000000.0,1.511000e+09,3.022800e+10,0.0,0.0,0.0,69209810.0,1.010463e+12

In [52]:
print('% de manioc exporté :', "{:.2f}".format(export_manioc["Exportations - Quantité"].iloc[0]*100/export_manioc["Production"].iloc[0]), "%")

% de manioc exporté : 83.41 %

In [53]:
# Pays au taux de sous-nutrition le plus élevé en 2017

In [54]:
prop_sous_nutrition

                                       Zone      Valeur  sous_nutrition
0                               Afghanistan  36296113.0      10500000.0
1                            Afrique du Sud  57009756.0       3100000.0
2                                   Albanie   2884169.0        100000.0
3                                   Algérie  41389189.0       1300000.0
4                                 Allemagne  82658409.0             0.0
..                                      ...         ...             ...
198  Venezuela (République bolivarienne du)  29402484.0       8000000.0
199                                Viet Nam  94600648.0       6500000.0
200                                   Yémen  27834819.0             0.0
201                                  Zambie  16853599.0             0.0
202                                Zimbabwe  14236595.0             0.0

[203 rows x 3 columns]

In [55]:
prop_sous_nutrition["S/V"] = prop_sous_nutrition["sous_nutrition"]/prop_sous_nutrition["Valeur"]

In [56]:
prop_sous_nutrition[prop_sous_nutrition["sous_nutrition"]>100000].sort_values(by="S/V", ascending=False).head(10)

,Zone,Valeur,sous_nutrition,S/V
78,Haïti,10982366.0,5300000.0,0.482592
157,République populaire démocratique de Corée,25429825.0,12000000.0,0.471887
108,Madagascar,25570512.0,10500000.0,0.410629
103,Libéria,4702226.0,1800000.0,0.382797
100,Lesotho,2091534.0,800000.0,0.382494
183,Tchad,15016753.0,5700000.0,0.379576
161,Rwanda,11980961.0,4200000.0,0.350556
121,Mozambique,28649018.0,9400000.0,0.328109
186,Timor-Leste,1243258.0,400000.0,0.321735
0,Afghanistan,36296113.0,10500000.0,0.289287

In [57]:
# Pays ayant reçu le plus d'aides alimentaires en 2017

In [58]:
aide_alimentaire

             Zone  Année                   Produit   Aide_kg
0     Afghanistan   2013       Autres non-céréales    682000
1     Afghanistan   2014       Autres non-céréales    335000
2     Afghanistan   2013              Blé et Farin  39224000
3     Afghanistan   2014              Blé et Farin  15160000
4     Afghanistan   2013                  Céréales  40504000
...           ...    ...                       ...       ...
1470     Zimbabwe   2015  Mélanges et préparations     96000
1471     Zimbabwe   2013              Non-céréales   5022000
1472     Zimbabwe   2014              Non-céréales   2310000
1473     Zimbabwe   2015              Non-céréales    306000
1474     Zimbabwe   2013                Riz, total     64000

[1475 rows x 4 columns]

In [59]:
aide_alimentaire.groupby("Zone").sum("Aide_kg").sort_values(by=["Aide_kg"], ascending=False).head(10)

                                  Année     Aide_kg
Zone
République arabe syrienne         76543  1858943000
Éthiopie                          66460  1381294000
Yémen                             76553  1206484000
Soudan du Sud                     44309   695248000
Soudan                            48335   669784000
Kenya                             54376   552836000
Bangladesh                        50347   348188000
Somalie                           54377   292678000
République démocratique du Congo  50350   288502000
Niger                             62448   276344000

In [60]:
# Top 5 pays avec le plus / moins de disponibilité alimentaire par habitant / par jour

In [61]:
dispo_alimentaire.groupby("Zone").sum("Disponibilité alimentaire (Kcal/personne/jour)").sort_values(by="Disponibilité alimentaire (Kcal/personne/jour)")

,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Valeur,dispo_kcal
Zone,,,,,,,,,,,,,,,,,
République centrafricaine,1.000000e+06,2.700000e+07,1879.0,453.73,59.41,46.04,2.582000e+09,0.000000e+00,7.600000e+07,2.092000e+09,1.220000e+08,2.503000e+09,6.300000e+07,2.780000e+08,3.000000e+06,3.906620e+08,3.152113e+12
Zambie,4.080000e+08,6.900000e+07,1924.0,350.12,42.05,55.22,1.004100e+10,6.750000e+08,3.800000e+08,5.088000e+09,2.420000e+08,1.052600e+10,7.600000e+07,4.178000e+09,-1.820000e+08,1.567385e+09,1.183561e+13
Madagascar,8.420000e+08,2.522000e+09,2056.0,425.07,24.49,46.69,1.521600e+10,2.360000e+08,9.240000e+08,9.741000e+09,9.660000e+08,1.416000e+10,3.750000e+08,8.440000e+08,3.750000e+08,2.352487e+09,1.918914e+13
Afghanistan,7.680000e+08,4.150000e+08,2087.0,351.41,33.50,58.26,1.351500e+10,2.780000e+08,2.988000e+09,1.073500e+10,1.135000e+09,1.117100e+10,3.950000e+08,6.300000e+07,-3.680000e+08,2.177767e+09,2.764875e+13
Haïti,4.810000e+08,1.150000e+08,2089.0,397.78,48.92,47.70,6.175000e+09,1.500000e+07,1.204000e+09,4.101000e+09,6.790000e+08,5.072000e+09,3.600000e+07,7.620000e+08,-7.700000e+07,9.554658e+08,8.373889e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Israël,2.525000e+09,8.010000e+08,3610.0,922.14,151.39,128.00,1.126700e+10,1.648000e+09,5.883000e+09,7.132000e+09,2.200000e+08,6.906000e+09,7.100000e+07,5.640000e+08,1.280000e+08,7.501902e+08,1.086251e+13
États-Unis d'Amérique,1.484320e+11,1.546990e+11,3682.0,1002.39,161.37,109.42,7.779920e+11,1.635240e+11,8.188700e+10,3.208890e+11,7.162000e+09,8.946680e+11,1.040300e+10,1.410100e+11,-3.503200e+10,3.088305e+10,4.368912e+14
Turquie,1.775000e+10,3.006000e+09,3708.0,968.15,119.64,108.12,1.313770e+11,1.459300e+10,1.213600e+10,7.255100e+10,1.203600e+10,1.374320e+11,2.553000e+09,2.356000e+10,-3.599000e+09,7.543830e+09,1.097846e+14
Belgique,5.533000e+09,3.226000e+09,3737.0,1002.09,161.95,99.37,2.935800e+10,3.034500e+10,3.527600e+10,1.113400e+10,5.640000e+08,2.449600e+10,1.530000e+08,8.960000e+09,-6.400000e+07,1.084876e+09,1.557659e+13
Autriche,3.412000e+09,1.001000e+09,3770.0,1069.20,170.44,106.20,1.930800e+10,6.733000e+09,8.463000e+09,9.085000e+09,4.590000e+08,1.812900e+10,1.730000e+08,5.178000e+09,-5.560000e+08,8.378906e+08,1.213662e+13

In [62]:
# Disponibilités en protéines

In [63]:
dispo_alimentaire.groupby("Zone").sum("Disponibilité de protéines en quantité (g/personne/jour)").sort_values(by="Disponibilité de protéines en quantité (g/personne/jour)")

,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Valeur,dispo_kcal
Zone,,,,,,,,,,,,,,,,,
Libéria,3.500000e+07,7.000000e+06,2206.0,385.48,59.85,37.66,2.002000e+09,3.400000e+07,4.700000e+08,1.653000e+09,1.110000e+08,1.533000e+09,16000000.0,1.790000e+08,35000000.0,3.432625e+08,3.786185e+12
Guinée-Bissau,5.000000e+06,1.400000e+07,2288.0,358.48,63.47,44.05,7.860000e+08,2.010000e+08,1.670000e+08,6.090000e+08,6.600000e+07,8.350000e+08,8000000.0,8.600000e+07,-17000000.0,1.334546e+08,1.526720e+12
Mozambique,1.720000e+09,2.204000e+09,2282.0,485.40,41.90,45.68,2.202300e+10,4.190000e+08,1.568000e+09,1.253800e+10,1.163000e+09,2.074200e+10,167000000.0,4.241000e+09,133000000.0,2.549763e+09,2.386263e+13
République centrafricaine,1.000000e+06,2.700000e+07,1879.0,453.73,59.41,46.04,2.582000e+09,0.000000e+00,7.600000e+07,2.092000e+09,1.220000e+08,2.503000e+09,63000000.0,2.780000e+08,3000000.0,3.906620e+08,3.152113e+12
Madagascar,8.420000e+08,2.522000e+09,2056.0,425.07,24.49,46.69,1.521600e+10,2.360000e+08,9.240000e+08,9.741000e+09,9.660000e+08,1.416000e+10,375000000.0,8.440000e+08,375000000.0,2.352487e+09,1.918914e+13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Maldives,0.000000e+00,5.600000e+07,2733.0,821.36,62.93,122.32,3.370000e+08,5.400000e+07,2.520000e+08,2.770000e+08,0.000000e+00,1.430000e+08,0.0,0.000000e+00,-3000000.0,4.318697e+07,4.951833e+11
Lituanie,1.933000e+09,4.160000e+08,3414.0,1050.07,94.44,124.36,7.467000e+09,5.963000e+09,3.060000e+09,3.169000e+09,1.470000e+08,9.761000e+09,381000000.0,1.426000e+09,616000000.0,2.589327e+08,3.545699e+12
Israël,2.525000e+09,8.010000e+08,3610.0,922.14,151.39,128.00,1.126700e+10,1.648000e+09,5.883000e+09,7.132000e+09,2.200000e+08,6.906000e+09,71000000.0,5.640000e+08,128000000.0,7.501902e+08,1.086251e+13
Chine - RAS de Hong-Kong,1.000000e+08,3.120000e+08,3286.0,802.17,139.82,129.07,6.424000e+09,3.604000e+09,9.510000e+09,5.778000e+09,2.160000e+08,4.700000e+08,2000000.0,1.100000e+07,44000000.0,7.014069e+08,8.763130e+12
Islande,1.070000e+08,4.300000e+07,3381.0,923.29,151.35,133.06,4.740000e+08,1.440000e+09,2.580000e+08,3.010000e+08,0.000000e+00,1.657000e+09,1000000.0,2.100000e+07,-2000000.0,3.009537e+07,4.126627e+11

In [64]:
# Pertes

In [65]:
dispo_alimentaire.groupby("Zone").sum("Pertes").sort_values(by="Pertes")

,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Valeur,dispo_kcal
Zone,,,,,,,,,,,,,,,,,
Islande,1.070000e+08,4.300000e+07,3381.0,923.29,151.35,133.06,4.740000e+08,1.440000e+09,2.580000e+08,3.010000e+08,0.000000e+00,1.657000e+09,1.000000e+06,2.100000e+07,-2.000000e+06,3.009537e+07,4.126627e+11
Kiribati,0.000000e+00,1.430000e+08,3042.0,667.19,103.40,73.34,2.410000e+08,4.500000e+07,2.400000e+07,6.700000e+07,0.000000e+00,2.690000e+08,0.000000e+00,2.900000e+07,-9.000000e+06,8.333534e+06,1.267531e+11
Maldives,0.000000e+00,5.600000e+07,2733.0,821.36,62.93,122.32,3.370000e+08,5.400000e+07,2.520000e+08,2.770000e+08,0.000000e+00,1.430000e+08,0.000000e+00,0.000000e+00,-3.000000e+06,4.318697e+07,4.951833e+11
Antigua-et-Barbuda,0.000000e+00,2.000000e+07,2416.0,694.17,89.76,83.49,7.900000e+07,0.000000e+00,6.300000e+07,5.800000e+07,0.000000e+00,2.000000e+07,0.000000e+00,0.000000e+00,-7.000000e+06,8.683766e+06,8.415046e+10
Bermudes,1.000000e+06,2.200000e+07,2668.0,840.70,109.93,90.36,5.900000e+07,2.400000e+07,7.700000e+07,5.100000e+07,0.000000e+00,6.000000e+06,0.000000e+00,0.000000e+00,0.000000e+00,5.106969e+06,6.139838e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Indonésie,9.531000e+09,3.422900e+10,2776.0,475.92,57.70,62.20,2.269300e+11,3.191200e+10,2.346600e+10,1.189140e+11,1.308100e+10,2.385590e+11,1.112000e+09,5.036500e+10,-3.182000e+09,2.540649e+10,2.681549e+14
Nigéria,3.602300e+10,1.671800e+10,2700.0,659.13,56.43,63.77,1.923880e+11,7.480000e+08,1.451000e+10,1.144390e+11,1.985400e+10,1.796310e+11,9.940000e+08,4.362000e+09,-9.990000e+08,1.736947e+10,1.881056e+14
Inde,4.912900e+10,1.516200e+10,2454.0,494.93,52.49,59.91,1.100838e+12,4.080700e+10,1.895400e+10,6.191680e+11,5.593000e+10,1.126270e+12,2.943200e+10,3.321230e+11,-3.573000e+09,1.298516e+11,1.199066e+15
Brésil,6.374000e+10,3.673000e+11,3262.0,779.79,117.72,95.01,1.033314e+12,1.265520e+11,1.681700e+10,1.562460e+11,7.591400e+10,1.143605e+12,2.884000e+09,3.672820e+11,-5.560000e+08,1.995205e+10,2.474532e+14
"Chine, continentale",3.459510e+11,7.868800e+10,3112.0,901.90,95.09,98.05,2.036726e+12,3.606000e+10,1.562460e+11,1.249625e+12,8.957500e+10,1.930913e+12,1.686000e+10,2.560680e+11,-1.437100e+10,1.364181e+11,1.614110e+15

In [66]:
# "Bons élèves"

In [67]:
dispo_alimentaire.groupby("Zone").sum("Pertes").sort_values(by="Pertes").head(10)

,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Valeur,dispo_kcal
Zone,,,,,,,,,,,,,,,,,
Islande,107000000.0,43000000.0,3381.0,923.29,151.35,133.06,474000000.0,1.440000e+09,258000000.0,301000000.0,0.0,1.657000e+09,1000000.0,21000000.0,-2000000.0,30095370.0,4.126627e+11
Kiribati,0.0,143000000.0,3042.0,667.19,103.40,73.34,241000000.0,4.500000e+07,24000000.0,67000000.0,0.0,2.690000e+08,0.0,29000000.0,-9000000.0,8333534.0,1.267531e+11
Maldives,0.0,56000000.0,2733.0,821.36,62.93,122.32,337000000.0,5.400000e+07,252000000.0,277000000.0,0.0,1.430000e+08,0.0,0.0,-3000000.0,43186974.0,4.951833e+11
Antigua-et-Barbuda,0.0,20000000.0,2416.0,694.17,89.76,83.49,79000000.0,0.000000e+00,63000000.0,58000000.0,0.0,2.000000e+07,0.0,0.0,-7000000.0,8683766.0,8.415046e+10
Bermudes,1000000.0,22000000.0,2668.0,840.70,109.93,90.36,59000000.0,2.400000e+07,77000000.0,51000000.0,0.0,6.000000e+06,0.0,0.0,0.0,5106969.0,6.139838e+10
Saint-Kitts-et-Nevis,0.0,35000000.0,2491.0,555.86,88.90,72.32,65000000.0,1.000000e+06,22000000.0,26000000.0,0.0,4.000000e+07,0.0,3000000.0,4000000.0,4319735.0,4.732009e+10
Chine - RAS de Macao,0.0,10000000.0,2915.0,655.38,126.18,94.75,383000000.0,2.000000e+06,367000000.0,368000000.0,1000000.0,1.600000e+07,0.0,3000000.0,2000000.0,56655235.0,6.624149e+11
Bahamas,1000000.0,96000000.0,2670.0,839.20,101.32,86.16,472000000.0,7.000000e+06,299000000.0,312000000.0,2000000.0,1.790000e+08,0.0,59000000.0,1000000.0,34357950.0,3.720393e+11
Barbade,31000000.0,28000000.0,2936.0,716.77,88.88,88.76,461000000.0,5.400000e+07,241000000.0,203000000.0,2000000.0,2.700000e+08,1000000.0,196000000.0,7000000.0,26333344.0,3.067377e+11
Grenade,14000000.0,10000000.0,2442.0,595.60,86.76,69.20,96000000.0,3.000000e+06,48000000.0,60000000.0,3000000.0,4.700000e+07,0.0,8000000.0,3000000.0,9646038.0,9.882532e+10

In [68]:
# "Mauvais élèves"

In [69]:
dispo_alimentaire.groupby("Zone").sum("Pertes").sort_values(by="Pertes").tail(10)

,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Valeur,dispo_kcal
Zone,,,,,,,,,,,,,,,,,
États-Unis d'Amérique,1.484320e+11,1.546990e+11,3682.0,1002.39,161.37,109.42,7.779920e+11,1.635240e+11,8.188700e+10,3.208890e+11,7.162000e+09,8.946680e+11,1.040300e+10,1.410100e+11,-3.503200e+10,3.088305e+10,4.368912e+14
Ghana,4.878000e+09,3.768000e+09,3014.0,867.95,45.94,64.57,3.899800e+10,1.495000e+09,3.427000e+09,2.248200e+10,7.442000e+09,3.658900e+10,7.700000e+07,4.290000e+08,4.820000e+08,2.737418e+09,3.203681e+13
Égypte,1.508400e+10,2.262000e+09,3518.0,803.79,63.09,103.22,1.151330e+11,5.014000e+09,2.410000e+10,6.595700e+10,7.608000e+09,9.584800e+10,1.365000e+09,2.292400e+10,1.990000e+08,9.065604e+09,1.238390e+14
Mexique,2.176500e+10,5.784000e+09,3068.0,680.85,93.47,87.58,1.867090e+11,1.976500e+10,3.251200e+10,8.329500e+10,8.289000e+09,1.708200e+11,7.370000e+08,6.689300e+10,3.147000e+09,1.185385e+10,1.397281e+14
Turquie,1.775000e+10,3.006000e+09,3708.0,968.15,119.64,108.12,1.313770e+11,1.459300e+10,1.213600e+10,7.255100e+10,1.203600e+10,1.374320e+11,2.553000e+09,2.356000e+10,-3.599000e+09,7.543830e+09,1.097846e+14
Indonésie,9.531000e+09,3.422900e+10,2776.0,475.92,57.70,62.20,2.269300e+11,3.191200e+10,2.346600e+10,1.189140e+11,1.308100e+10,2.385590e+11,1.112000e+09,5.036500e+10,-3.182000e+09,2.540649e+10,2.681549e+14
Nigéria,3.602300e+10,1.671800e+10,2700.0,659.13,56.43,63.77,1.923880e+11,7.480000e+08,1.451000e+10,1.144390e+11,1.985400e+10,1.796310e+11,9.940000e+08,4.362000e+09,-9.990000e+08,1.736947e+10,1.881056e+14
Inde,4.912900e+10,1.516200e+10,2454.0,494.93,52.49,59.91,1.100838e+12,4.080700e+10,1.895400e+10,6.191680e+11,5.593000e+10,1.126270e+12,2.943200e+10,3.321230e+11,-3.573000e+09,1.298516e+11,1.199066e+15
Brésil,6.374000e+10,3.673000e+11,3262.0,779.79,117.72,95.01,1.033314e+12,1.265520e+11,1.681700e+10,1.562460e+11,7.591400e+10,1.143605e+12,2.884000e+09,3.672820e+11,-5.560000e+08,1.995205e+10,2.474532e+14
"Chine, continentale",3.459510e+11,7.868800e+10,3112.0,901.90,95.09,98.05,2.036726e+12,3.606000e+10,1.562460e+11,1.249625e+12,8.957500e+10,1.930913e+12,1.686000e+10,2.560680e+11,-1.437100e+10,1.364181e+11,1.614110e+15

In [70]:
# Merci de m'avoir écouté !